sp                <- ' '   
                  / '\n'   
                  / '\t'   .
_               <- sp _   
                  /    .
rule              <- n: name _ '<-' _ body: choice '.' _ -> (format(["function parse_",
           vars["n"],
           "(input, pos) { let state = { pos: pos }; ",
           "let vars = {}",
           vars["body"],
           " return state; }"]))
 .
grammar           <- _ r: rule g: grammar -> (format([vars["r"], " ", vars["g"]]))
 
                  / _ r: rule -> (format(["// This is from a template in peg.org:\n", vars["r"], 
   ` function parse_char(input, pos) {
     if (pos >= input.length) return null;
     return { pos: pos + 1, val: input.charAt(pos) };
   }
   function literal(input, pos, string) {
     if (input.substr(pos, string.length) === string) {
       return { pos: pos + string.length, val: string };
     } else return null;
   }

   let stack = []

   // let strbuf = new Uint8Array(65536)
   let strbuf = []

   let format = (parts) => {
     return parts.join('')
   }
   var fs = require(\'fs\');
   var grammarfile = process.argv.slice(2)[0];
   fs.readFile(grammarfile, function(err, data) {
       if (err) {
           throw err; 
       }
       var out = parse_grammar(data.toString(), 0);
       console.log(out.val);
   });`]))
 .
meta              <- '!'   
                  / '\''   
                  / '<-'   
                  / '/'   
                  / '.'   
                  / '('   
                  / ')'   
                  / ':'   
                  / '->'   .
name              <- c: namechar n: name -> (format([vars["c"], vars["n"]]))
 
                  / namechar   .
namechar          <- !meta !sp char   .
term              <- labeled   
                  / nonterminal   
                  / string   
                  / negation   
                  / parenthesized   .
nonterminal       <- n: name _ -> (format(["state = parse_", vars["n"], "(input, state.pos);"]))
 .
labeled           <- label: name _ ':' _ value: term -> (format([vars["value"],
           " if (state) { vars[\"",
           vars["label"],
           "\"] = state.val; }"]))
 .
sequence          <- foo: term  bar: sequence -> (format([vars["foo"],
           " if (state) { ",
           vars["bar"],
           " } "]))
 
                  / result_expression   
                  /  -> ("")
 .
string            <- '\'' s: stringcontents '\'' _ -> (format(["state = literal(input, state.pos, \"",
           vars["s"],
           "\");"]))
 .
stringcontents    <- !'\\' !'\'' c: char s: stringcontents -> (format([vars["c"], vars["s"]]))
 
                  / b: '\\' c: char s: stringcontents -> (format([vars["b"], vars["c"], vars["s"]]))
 
                  /  -> ("")
 .
choice            <- a: sequence '/' _  b: choice -> (format(["stack.push(state); ",
	      vars["a"],
	      " if (!state) {state = stack.pop(); ",
	      vars["b"],
	      "} else { stack.pop(); }"]))
 
                  / sequence   .
negation          <- '!' _ t: term -> (format([" stack.push(state);",
            vars["t"], 
            "if (state) { stack.pop(); state = null; }",
            "else { state = stack.pop(); }"]))
 .
result_expression <- '->' _ result: expr _ -> (format(["if (state) { state.val = ",
           vars["result"],
           "; }"]))
 .
expr              <- '(' _ e: exprcontents ')' -> (format(["(", vars["e"], ")"]))
 .
exprcontents      <- c: (!'(' !')' (location / char) / expr) e: exprcontents -> (format([vars["c"], vars["e"]]))
 
                  /  -> ("")
 .
location          <- '§' n: name -> ("POOP")
 .
parenthesized     <- '(' _ body: choice ')' _ -> (format([vars["body"]]))
 .